;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC etcdserverpb.Watch Client Implementation
;;;----------------------------------------------------------------------------------
(ns etcdserverpb.Watch.client
  (:require [etcdserverpb :refer :all]
            [authpb :as authpb]
            [mvccpb :as mvccpb]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn Watch
  [client params reply]
  (let [desc {:service "etcdserverpb.Watch"
              :method  "Watch"
              :input   {:f etcdserverpb/new-WatchRequest :ch params}
              :output  {:f etcdserverpb/pb->WatchResponse :ch reply}}]
    (grpc/invoke client desc)))

